import { useState } from "react";
import Map from "./Map";
import cs from "classnames";
import "../stylesheets/Travels.scss";
import useWindowDimensions from "../utils/windowResize";
import Burger from "./helper/Burger";

const TravelsPage = () => {
  const [clicked, setClicked] = useState(null);
  const [info, setInfo] = useState({});
  const { width } = useWindowDimensions();

  return (
    <div className="map-container">
      <Map onMarkerClick={(data) => setInfo(data)} />
      <div className="map-floater bg-zinc-50 drop-shadow-xl rounded-md py-1 pr-1 pl-2.5 mx-auto">
        <div className="flex font-bold text-3xl items-center">
          <div className="mr-1">DWU Reviews</div>
        </div>
        <Burger />
      </div>
      <div
        className={cs({
          "overflow-y-scroll rounded": clicked,
          "overlay-max": clicked,
          "overlay-min w-128 drop-shadow-2xl cursor-pointer rounded-md mb-10 text-xl font-bold hover:bg-slate-900 hover:text-white":
            !clicked,
          "z-hidden": clicked === null,
          "z-regular": info.name,
        })}
        style={
          clicked
            ? {}
            : {
                marginLeft: (width - 512) / 2,
                marginRight: (width - 512) / 2,
              }
        }
      >
        <div
          onClick={() => setClicked(false)}
          className={!clicked ? "hidden" : "cursor-pointer rounded text-center"}
        >
          <div className="w-12 mx-auto bg-slate-400 text-white rounded-b-md">
            <i className="fa-solid fa-angles-down mt-1.5"></i>
          </div>
        </div>
        <div
          onClick={() => {
            if (!clicked) {
              setClicked(true);
            }
          }}
          className={`my-4 mx-6 text-center ${
            clicked ? "title-wrap" : "title-ellipsis"
          }`}
        >
          {info.name}
        </div>
        <div className={clicked ? "mx-12" : "hidden"}>
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
          HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLD
        </div>
      </div>
    </div>
  );
};

export default TravelsPage;
